// DO NOT EDIT. this file is generated by gqlcodegen.
package example

import (
	"github.com/RettyInc/gqlcodegen/example/enum/class"
)

type DriverResolver interface {

	// Return value of LicenceNumber is nullable
	LicenceNumber() *string
	Name() string

	// Return value of MiddleName is nullable
	MiddleName() *string
	FamilyName() string
	IsOnDuty() bool
	Class() class.Class
}
