// DO NOT EDIT. this file is generated by gqlcodegen.
package example

import (
	"github.com/RettyEng/gqlcodegen/example/enum/class"
)

type DriverResolver interface {

	// Return value of LicenceNumber is nullable
	LicenceNumber() *string
	Name() string

	/*
	   Directives:
	     @withContext()
	*/
	// Return value of MiddleName is nullable
	MiddleName(context.Context) *string
	FamilyName() string
	IsOnDuty() bool
	Class() class.Class
}
