// DO NOT EDIT. this sourcecode is generated by gqlcodegen.
package example

import (
	"context"

	"github.com/RettyInc/gqlcodegen/example/enum/class"
	"github.com/RettyInc/gqlcodegen/example/scalar"
)

type GarageResolver interface {
	Id() scalar.Uint32
	Trucks(context.Context, GarageResolver_Trucks_Arg) []TruckResolver
	Drivers(context.Context, GarageResolver_Drivers_Arg) []DriverResolver
	Trailers(context.Context, GarageResolver_Trailers_Arg) []TrailerResolver
}

type GarageResolver_Trucks_Arg struct {
	Size   scalar.Uint32
	Cursor *scalar.Cursor
}

type GarageResolver_Drivers_Arg struct {
	Size   scalar.Uint32
	Class  []class.Class
	Cursor *scalar.Cursor
}

type GarageResolver_Trailers_Arg struct {
	Size   scalar.Uint32
	Cursor *scalar.Cursor
}
