// DO NOT EDIT. this sourcecode is generated by gqlcodegen.
package example

import (
	"context"

	"github.com/RettyInc/gqlcodegen/example/scalar"
)

type QueryResolver interface {

	// Return value of Truck is nullable
	Truck(context.Context, QueryResolver_Truck_Arg) TruckResolver

	// Return value of Garage is nullable
	Garage(context.Context, QueryResolver_Garage_Arg) GarageResolver
}

type QueryResolver_Truck_Arg struct {
	Number *scalar.RegistrationNumber
}

type QueryResolver_Garage_Arg struct {
	Id scalar.Uint32
}
