// DO NOT EDIT. this file is generated by gqlcodegen.
package example

import (
	"github.com/RettyEng/gqlcodegen/example/enum/maker"
	"github.com/RettyEng/gqlcodegen/example/scalar"
)

/*
   Description:
     """
     This is truck
     """
   Directives:
     @special()
*/
type TruckResolver interface {
	Maker() maker.Maker

	/*
	   Description:
	     "Number"
	   Directives:
	     @hoge()
	*/
	Number() scalar.RegistrationNumber
	Capacity() int

	// Return value of EnginePower is nullable
	EnginePower() *int
}
