// DO NOT EDIT. this file is generated by gqlcodegen.
package example

import (
	"github.com/RettyInc/gqlcodegen/example/enum/maker"
	"github.com/RettyInc/gqlcodegen/example/scalar"
)

/*
   Description:
     """
     This is truck
     """
*/
type TruckResolver interface {
	Maker() maker.Maker

	/*
	   Description:
	     "Number"
	   Directives:
	     @hoge()
	*/
	Number() scalar.RegistrationNumber
	Capacity() int
}
