// DO NOT EDIT. this file is generated by gqlcodegen.
package maker

/*
   Directives:
     @important()
*/
type Maker int

const (

	/*
	   Description:
	     "Scania is awesome"
	*/
	SCANIA Maker = iota
	DAF
	MAN
	RENAULT
	MERCEDES
	IVECO
	VOLVO

	/*
	   Directives:
	     @deprecated(reason: "not an euro truck")
	*/
	ISUZU
)

//go:generate stringer -type=Maker
