// DO NOT EDIT. this sourcecode is generated by gqlcodegen.
package maker

type Maker int

const (
	SCANIA Maker = iota
	DAF
	MAN
	RENAULT
	MERCEDES
	IVECO
	VOLVO
)

//go:generate stringer -type=Maker
