// DO NOT EDIT. this file is generated by gqlcodegen.
package class

type Class int

const (
	ROOKIE Class = iota
	ELITE

	/*
	   Directives:
	     @special()
	*/
	KING_OF_ROAD
	LEGEND
)

//go:generate stringer -type=Class
