// Code generated by "stringer -type=Type"; DO NOT EDIT.

package token

import "strconv"

const _Type_name = "TypeUnicodeBomTypeWhiteSpaceTypeLineTerminatorTypeCommaTypePunctuatorTypeCommentTypeNameTypeIntValTypeFloatValTypeStrVal"

var _Type_index = [...]uint8{0, 14, 28, 46, 55, 69, 80, 88, 98, 110, 120}

func (i Type) String() string {
	if i < 0 || i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
