package generator

import (
	"github.com/RettyInc/gqlcodegen/ast"
	"strings"
)

func generateEnum(g *Generator, def *ast.EnumDef) {
	g.Printf("// DO NOT EDIT. this sourcecode is generated by gqlcodegen.\n")
	generateEnumPackageSection(g, def)
	g.Printf("\n")
	generateEnumTypeDefSection(g, def)
	g.Printf("\n")
	generateEnumConstSection(g, def)
	g.Printf("\n")
	g.Printf("//go:generate stringer -type=%s\n", capitalizeFirst(def.Name()))
}

func generateEnumPackageSection(g *Generator, def *ast.EnumDef) {
	g.Printf("package %s\n", strings.ToLower(def.Name()))
}

func generateEnumTypeDefSection(g *Generator, def *ast.EnumDef) {
	g.Printf("type %s int\n", capitalizeFirst(def.Name()))
}

func generateEnumConstSection(g *Generator, def *ast.EnumDef) {
	g.Printf("const(\n")
	generateEnumConstBody(g, def)
	g.Printf(")\n")
}

func generateEnumConstBody(g *Generator, def *ast.EnumDef) {
	entries := def.Entries()
	for i, e := range entries {
		g.Printf("%s", capitalizeFirst(e.Name()))
		if i == 0 {
			g.Printf(" %s = iota", capitalizeFirst( def.Name()))
		}
		g.Printf("\n")
	}
}


