// Code generated by "stringer -type=Location"; DO NOT EDIT.

package directive

import "strconv"

const _Location_name = "QUERYMUTATIONSUBSCRIPTIONFIELDFRAGMENT_DEFINITIONFRAGMENT_SPREADINLINE_FRAGMENTVARIABLE_DEFINITIONSCHEMASCALAROBJECTFIELD_DEFINITIONARGUMENT_DEFINITIONINTERFACEUNIONENUMENUM_VALUEINPUT_OBJECTINPUT_FIELD_DEFINITION"

var _Location_index = [...]uint8{0, 5, 13, 25, 30, 49, 64, 79, 98, 104, 110, 116, 132, 151, 160, 165, 169, 179, 191, 213}

func (i Location) String() string {
	if i < 0 || i >= Location(len(_Location_index)-1) {
		return "Location(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Location_name[_Location_index[i]:_Location_index[i+1]]
}
